name: Deployment to server
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: vps-2b071dcc
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: |
          npm i
          npm run build
          sudo service nginx restart
